[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn 'app:create_app()' --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/auth/login"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
